---
# playbook.yaml
- name: "Install Boundary"
  hosts: default
  remote_user: ubuntu
  gather_facts: true
  become: true
  vars:
    boundary_version: 0.1

  tasks:
    - name: Add HashiCorp repo key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com bionic main
        state: present

    - name: Upgrade installed packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: latest

    - name: Install Boundary
      apt:
        name: boundary
        state: latest

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest
      with_items:
        - postgresql-contrib

    - name: Install psycopg2 for postgresql user creation
      pip:
        name: psycopg2-binary
        executable: pip3

    - name : Create Boundary user on postgres
      become_user: postgres
      community.general.postgresql_user:
        name: boundary
        password: boundary
        role_attr_flags: SUPERUSER
        state: present

    - name: Create Boundary Database
      become_user: postgres
      community.general.postgresql_db:
        name: boundary
        owner: boundary

    - name: Create Boundary Group
      group:
        name: boundary
        state: present

    - name: Create Boundary User
      user:
        name: boundary
        state: present
        system: yes

    - name: Copy Boundary systemd
      copy:
        src: ./boundary.service
        dest: /etc/systemd/system/boundary.service
        owner: boundary
        group: boundary
        mode: '0664'

    - name: Change Boundary file permissions
      file:
        path: /usr/bin/boundary
        owner: boundary
        group: boundary

    - name: Disable boundary Service
      systemd:
        name: boundary
        enabled: no