#cloud-config
write_files:
  - path: /etc/boundary.d/config.hcl
    content: ${boundary_conf}
    permissions: '0644'
    owner: boundary:boundary
    encoding: b64

runcmd:
  - BOUNDARY_INIT=$(sudo boundary database init -skip-host-resources-creation -skip-scopes-creation -skip-target-creation -config /etc/boundary.d/config.hcl || true)
  - echo $BOUNDARY_INIT | sudo tee -a /etc/boundary.d/init.log
  - sudo systemctl enable boundary
  - sudo systemctl restart boundary